# Generated by Django 2.1.5 on 2019-03-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='gpa',
            name='grade',
            field=models.CharField(help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=200),
        ),
    ]
