# Generated by Django 2.1.5 on 2019-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_scholarship_disbursement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='disbursement',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='value',
            field=models.CharField(default=100, help_text='Ammount distributed', max_length=13, verbose_name='Value'),
            preserve_default=False,
        ),
    ]
