# Generated by Django 2.1.5 on 2019-03-29 23:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20190314_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarshipinstance',
            options={'ordering': ['deadline'], 'permissions': (('can_mark_returned', 'Set scholarship as applied'),)},
        ),
        migrations.AddField(
            model_name='scholarshipinstance',
            name='imprint',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gpa',
            name='grade',
            field=models.CharField(help_text='Enter the min gpa required to apply ', max_length=200),
        ),
        migrations.AlterField(
            model_name='scholarshipinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular scholarship across whole Archive', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scholarshipinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Maintenance'), ('o', 'Waitlist'), ('a', 'Available'), ('r', 'Rewarded')], default='d', help_text='Scholarship availability', max_length=1),
        ),
    ]
