# Generated by Django 2.1.5 on 2019-04-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20190329_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Applied'), ('o', 'Waitlist'), ('a', 'Available'), ('r', 'Rewarded')], default='d', help_text='Scholarship availability', max_length=1),
        ),
    ]
