# Generated by Django 2.1.5 on 2019-04-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20190403_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarshipinstance',
            options={'ordering': ['deadline'], 'permissions': (('can_mark_awarded', 'Set scholarship as applied'),)},
        ),
    ]
