# Generated by Django 2.1.5 on 2019-04-09 01:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20190403_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular student', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('applied_scholarships', models.ManyToManyField(to='archive.ScholarshipInstance')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
